# Generated by Django 3.2.7 on 2021-10-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.TextField(null=True)),
                ('img', models.TextField(null=True)),
            ],
        ),
    ]
